#
# Configuration for the qmanager module
#

[qmanager]

queue-policy = "fcfs"                 # queueing policy type

# general queue parameters
    # max queue depth (applied to all policies)
    # queue-depth (applied to all policies)
    # unknown key should be tolerated
queue-params = "max-queue-depth=1000"

# queue policy parameters
    # max depth for "conservative" and "hybrid"
    # reservation depth for HYBRID
policy-params = "max-reservation-depth=100000,reservation-depth=64"
