coverage:
 precision: 1
 round: down
 range: "50...100"
 ignore:
 - ".*/test/*.c"
 - ".*/tests/*.c"
 - ".*/libtap/*"
 - ".*/libjsonc/*"
 - ".*/libev/*"
 patch:
  default:
   target: 50%
 comment:
  layout: "header, diff, changes, tree"
