#
# Configuration for the qmanager module
#

[qmanager]

policy = "fcfs"                    # queueing policy type

    [qmanager.policy-params]       # queue policy parameters
    max-reservation-depth = 100000 # max depth for "conservative" and "hybrid"
    reservation-depth = 64         # reservation depth for HYBRID

