#
# Configuration for the qmanager module
#

[sched-fluxion-qmanager]

queue-policy = "fcfs"                    # queueing policy type

# queue policy parameters
    # max depth for "conservative" and "hybrid"
    # reservation depth for HYBRID
[sched-fluxion-qmanager.policy-params]

max-reservation-depth = 100000
reservation-depth = 64

