[sched-fluxion-resource]

# support for node, core and gpu type if hwloc is used
load-allowlist="node,core,gpu"

# system instance will use node-exclusive
# scheduling (with nodes of low node IDs
# selected first).
match-policy = "lonodex"

# system-instance will use full-up rv1 writer
# so that R will contain scheduling key needed
# for failure recovery.
match-format = "rv1"

prune-filters="ALL:core"

