#
# Configuration for the qmanager module
#

[sched-fluxion-qmanager]

# queueing policy type
queue-policy = "easy"

# general queue parameters
    # queue-depth (applied to all policies)
    # max queue depth (applied to all policies)
[sched-fluxion-qmanager.queue-params]

queue-depth = 8192
max-queue-depth = 1000000

# queue policy parameters
    # max depth for "conservative" and "hybrid"
    # reservation depth for HYBRID
[sched-fluxion-qmanager.policy-params]

reservation-depth = 64
max-reservation-depth = 100000

