#
# Configuration for the qmanager module
#

[qmanager]

# multiple queues
queues = "debug batch"

# queueing policy type
queue-policy-per-queue = "debug:fcfs batch:hybrid"

# general queue parameters
    # max queue depth (applied to all policies)
    # queue-depth (applied to all policies)
queue-params-per-queue = "debug:queue-depth=16"

# queue policy parameters
    # max depth for "conservative" and "hybrid"
    # reservation depth for HYBRID
policy-params-per-queue = "batch:max-reservation-depth=100000,reservation-depth=64"
