#
# Configuration for the qmanager module
#

[sched-fluxion-qmanager]

queue-policy = "easy"

# multiple queues
queues = "debug batch"

# queueing policy type for one or more named queue
#     batch should inherit the base policy (easy)
queue-policy-per-queue = "debug:fcfs"

# general queue parameters
    # max queue depth (applied to all policies)
    # queue-depth (applied to all policies)
queue-params-per-queue = "debug:queue-depth=16"

# general queue parameters
    # max queue depth (applied to all policies)
    # queue-depth (applied to all policies)
#queue-params = "max-queue-depth=1000000,queue-depth=8192"
[sched-fluxion-qmanager.queue-params]

max-queue-depth = 1000000
queue-depth = 8192

