#
# Configuration for the qmanager module
#

[sched-fluxion-qmanager]

queue-policy = "fcfs"              # queueing policy type

# general queue parameters
    # max queue depth (applied to all policies)
    # queue-depth (applied to all policies)
    # unknown key should be tolerated
[sched-fluxion-qmanager.queue-params]

max-queue-depth = 1000000
queue-depth = 8192
foo = 1234

# queue policy parameters
    # max depth for "conservative" and "hybrid"
    # reservation depth for HYBRID
[sched-fluxion-qmanager.policy-params]

max-reservation-depth = 100000
reservation-depth = 64

